---
name: AWS OIDC List Buckets 

on: [workflow_dispatch]

jobs:
  list-s3-buckets:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Debug OIDC Claims
        uses: github/actions-oidc-debugger@main
        with:
          audience: sts.amazonaws.com
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          role-session-name: GitHubActions
          aws-region: "eu-west-1"

      - name: Get current buckets
        run: |
          aws s3 ls
