---
name: AWS S3 List Buckets

on: [workflow_dispatch]

jobs:
  list-s3-buckets:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Get current buckets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 ls
